spring:
  session:
    store-type: none
  mvc:
    favicon:
      enabled: false
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 12
      max-wait: 60000
      test-while-idle: true
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: true
      min-evictable-idle-time-millis: 60000
      time-between-eviction-runs-millis: 5000
      max-active: 100
      min-idle: 5
      remove-abandoned: true
      remove-abandoned-timeout: 60
      log-abandoned: true
      use-disposable-connection-facade: true
      validation-interval: 5000

endpoints:
  health:
    mapping:
      DOWN: SERVICE_UNAVAILABLE
      UNKNOWN: SERVICE_UNAVAILABLE
      OUT_OF_SERVICE: SERVICE_UNAVAILABLE
    sensitive: true

management:
  endpoints:
    web:
      base-path: /